service: mcdiscordbot


# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-west-2
  iam:
    role:
      statements:

        - Effect: "Allow"
          Action:
            - "ec2:DescribeInstances"
            - "ec2:StartInstances"
            - "ec2:StopInstances"
            - "ce:*"
          Resource: 
            - "*"

        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: 
            - "arn:aws:sns:us-west-2:621056530958:minecraft-alert"

        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
          Resource:
            - "arn:aws:dynamodb:us-west-2:621056530958:table/minecraft_players"
      
        - Effect: "Allow"
          Action:
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:CreateNetworkInterface"
            - "ec2:DeleteNetworkInterface"
            - "ec2:DescribeInstances"
            - "ec2:AttachNetworkInterface"
          Resource:
            - "*"

plugins:
  - serverless-python-requirements
  - serverless-add-api-key
custom:
  pythonRequirements:
    dockerizePip: True
  apiKeys:
    - name: discordBot

package:
  individually: True
  exclude:
    # Exclude everything first.
    - '**/*'

functions:

  # Main function for taking start and stop actions.
  ec2Action:
    handler: action/action.handler
    events:
      - http:
          path: action
          method: post
          private: True
    package:
      include:
        - action/**
    environment:
      region: us-west-2
  # Function for using mcstatus to check if a mc server is running 
  getStatus:
    handler: status/status.handler
    events:
      - http:
          path: status
          method: get
          # private: True
    package:
      include:
        - status/**

  # Function for listing EC2 minecraft servers based on tags
  listServers:
    handler: list/list.handler
    events:
      - http:
          path: list
          method: get
          private: True
    package:
      include:
        - list/**

  # Function for SNS to send message to discord
  # Triggered by SNS
  sendDiscordMessage:          
    handler: sendDiscordMessage/send.handler
    events:
      - sns:
          arn: arn:aws:sns:us-west-2:621056530958:minecraft-alert
    package:
      include:
        - sendDiscordMessage/**
    environment:
      webhook: https://discord.com/api/webhooks/824478695006928956/O38JRoxLSANII8F8c_ykgPLt7-DcFaIycWiL05kPGwgfs8G17A_NNkZyRCN3mPP_fUaZ

  # Function to check account total per month.
  # Triggered by cloudwatch

  billingNotification:          
    handler: billingNotifiy/notify.handler
    events:
      - schedule: rate(15 days)
    package:
      include:
        - billingNotifiy/**
  
  # Allow users to read player billing 
  playerBilling:          
    handler: playerBilling/playerBilling.handler
    events:
      - http:
          path: playerBilling
          method: get
          private: True
    package:
      include:
        - playerBilling/**

  mcCommand:          
    handler: mccommand/command.handler
    events:
      - http:
          path: cmd
          method: post
          private: True
    environment:
      rconpass: 8h8AT3zVjPUGgrsQxc
    package:
      include:
        - mccommand/**

        