
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - openjdk-17-jdk  
      - git
      - python3-pip
      - zip
      - collectd
    update_cache: yes
  become: true 

- name: Install boto3 python package
  ansible.builtin.pip:
    name: boto3

- amazon.aws.ec2_metadata_facts:

- name: Retrieve all tags on an instance
  amazon.aws.ec2_tag_info:
    resource: "{{ansible_ec2_instance_id}}"
    region: us-west-2
  register: instance_tags

- name: Create server directory if it does not exist
  ansible.builtin.file:
    path: /home/ubuntu/server/
    state: directory
    mode: '0755'

- name: Create scripts directory if it does not exist
  ansible.builtin.file:
    path: /home/ubuntu/scripts/
    state: directory
    mode: '0755'

- name: Write eula
  copy:
    dest: "/home/ubuntu/server/eula.txt"
    content: "eula=true"

- name: Your copy task
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '../files/scripts', dest: '/home/ubuntu/' }

- name: Download mcrcon
  amazon.aws.aws_s3:
    bucket: "{{s3_files_bucket}}"
    object: rcon/mcrcon-0.7.2-linux-x86-64.tar.gz
    dest: /tmp/mcrcon-0.7.2-linux-x86-64.tar.gz
    mode: get

- name: Make scripts executable 
  file: path=/home/ubuntu/scripts owner=ubuntu group=ubuntu mode=0775 state=directory recurse=yes

- name: Extract mcrcon
  ansible.builtin.unarchive:
    src: /tmp/mcrcon-0.7.2-linux-x86-64.tar.gz
    dest: /usr/local/bin/
    remote_src: true
  become: true

- name: Pull existing world save (if exists)
  block:

  - name: Pull world
    ansible.builtin.shell: "aws s3 cp s3://{{s3_world_bucket}}/worlds/mc.{{instance_tags['tags']['Name']}}.zip /tmp/"

  - name: Extract world
    ansible.builtin.unarchive:
      src:  "/tmp/mc.{{instance_tags['tags']['Name']}}.zip"  
      dest: /home/ubuntu/server
      remote_src: yes
  rescue:
    - name: Failed to pull or Extract world
      ansible.builtin.debug:
        msg: 'Failed to pull or extract existing world save, does it exist?'

- name: Setup auto shutdown cron job
  ansible.builtin.cron:
    name: "auto shutdown"
    minute: "15"
    weekday: "*"
    hour: "*"
    job: "/bin/bash /home/ubuntu/scripts/stop-check.sh >> /home/ubuntu/cron.log 2>&1"

- name: Setup auto shutdown cron job
  ansible.builtin.cron:
    name: "billing player check"
    minute: "10"
    weekday: "*"
    hour: "*"
    job: "/bin/bash /home/ubuntu/scripts/backup-world.sh >> /home/ubuntu/cron.log 2>&1"

- name: Setup dns cron job
  ansible.builtin.cron:
    name: "Update DNS at reboot"
    special_time: reboot
    job: "/bin/bash /home/ubuntu/scripts/update-dns.sh >> /home/ubuntu/cron.log 2>&1"

- name: Download cloudwatch agent
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /tmp/amazon-cloudwatch-agent.deb

- name: Install cloudwatch agent 
  ansible.builtin.shell: dpkg -i -E /tmp/amazon-cloudwatch-agent.deb
  become: true

- name: Copy file with owner and permission, using symbolic representation
  ansible.builtin.copy:
    src: ../files/cloudwatch.conf
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
  become: true

- name: Install cloudwatch agent 
  ansible.builtin.shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
  become: true