service: mcdiscordbot

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  iam:
    role:
      statements:

        - Effect: "Allow"
          Action:
            - "ec2:DescribeInstances"
            - "ec2:StartInstances"
            - "ec2:StopInstances"
            - "ce:*"
          Resource: 
            - "*"

        - Effect: "Allow"
          Action:
            - "ssm:SendCommand"
          Resource: 
            - "*"

        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: 
            - !Ref mcalerts

        - Effect: "Allow"
          Action:
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:PutItem"
          Resource:
            - ${ssm:/mc/mcdata}
      
        - Effect: "Allow"
          Action:
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:CreateNetworkInterface"
            - "ec2:DeleteNetworkInterface"
            - "ec2:DescribeInstances"
            - "ec2:AttachNetworkInterface"
          Resource:
            - "*"

plugins:
  - serverless-python-requirements
  - serverless-add-api-key
custom:
  apiKeys:
    - name: discordBot
  pythonRequirements:
   pythonBin: python3

package:
  individually: True
  patterns:
    - '!**/*' # exclude everting
    - 'functions/shared/**' 

functions:

  # Main function for taking start and stop actions.
  ec2Action:
    handler: functions/action/action.handler
    events:
      - http:
          path: action
          method: post
          private: True
    package:
      include:
        - functions/action/**
        - functions/shared/**
    environment:
      region: us-west-2
      rconpass: ${ssm:/mc/rconpass}

  # Function for listing EC2 minecraft servers based on tags
  listServers:
    handler: functions/list/list.handler
    events:
      - http:
          path: list
          method: get
          private: True
    package:
      include:
        - functions/list/**

  # Function for SNS to send message to discord
  # Triggered by SNS
  sendDiscordMessage:          
    handler: functions/sendDiscordMessage/send.handler
    events:
      - sns:
          arn: !Ref mcalerts
          topicName: mcalerts
    package:
      include:
        - functions/sendDiscordMessage/**
    environment:
      webhook: ${ssm:/mc/discord-webhook}

  # Function to check account total per month.
  # Triggered by cloudwatch

  billingNotification:          
    handler: functions/billingNotifiy/notify.handler
    events:
      - schedule: rate(15 days)
    package:
      include:
        - functions/billingNotifiy/**
  
  # Allow users to read player billing 
  playerBilling:          
    handler: functions/listPlayerBilling/listPlayerBilling.handler
    events:
      - http:
          path: listPlayerBilling
          method: get
          private: True
    package:
      include:
        - functions/listPlayerBilling/**

  # Function to bill active users on servers

  managePlayerBilling:          
    handler: functions/managePlayerBilling/managePlayerBilling.handler
    events:
      - schedule: rate(1 minute)
    package:
      include:
        - functions/managePlayerBilling/**

resources:
  Resources:
    mcalerts:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: mcalerts       