# - name: Install a list of packages
#   ansible.builtin.apt:
#     pkg:
#       - openjdk-8-jre
#     update_cache: yes
#   become: true 

# - name: Set default java version to jdk 8
#   ansible.builtin.shell: update-alternatives --set  java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
#   become: true


# - name: Download forge-1.12.2-14.23.5.2860 installer
#   amazon.aws.aws_s3:
#     bucket: "{{s3_files_bucket}}"
#     object: /serverjar/forge-1.12.2-14.23.5.2860-installer.jar
#     dest: /home/ubuntu/server/forge-1.12.2-14.23.5.2860-installer.jar
#     mode: get

# - name: Install server
#   ansible.builtin.shell: java -jar forge-1.12.2-14.23.5.2860-installer.jar --installServer
#   args:
#     chdir: /home/ubuntu/server/

- name: Download Chocolate Mods Zip
  amazon.aws.aws_s3:
    bucket: "{{s3_files_bucket}}"
    object: "/mods/Chocolate-Edition-Server-Pack-1.4.3.zip"
    dest: /tmp/Chocolate-Edition-Server-Pack-1.4.3.zip
    mode: get

- name: Extract mods to server dir
  ansible.builtin.unarchive:
    src:  "/tmp/Chocolate-Edition-Server-Pack-1.4.3.zip"  
    dest: /home/ubuntu/server
    remote_src: yes

- name: Overwrite server.properties files 
  template:
    src: "./files/server.properties"
    dest: /home/ubuntu/server

- name: Make start file executable
  ansible.builtin.file:
    path: /home/ubuntu/server/start.sh
    mode: 0755

- name: Write Java args to var file
  ansible.builtin.shell: echo "-Xmx15G" >> /home/ubuntu/server/user_jvm_args.txt

- name: template file to remote host
  template:                 # Ansible template module
    src: "../files/systemd.j2"      # This is template src i.e source location 
    dest: /etc/systemd/system/minecraft.service    # Destination of Remote host
  become: true
  
- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enable the minecraft server
  ansible.builtin.systemd:
    name: minecraft
    state: started
    enabled: yes
  become: true
